version: '2.3.3'
services:
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

  features:
        build:
            context: ./features
        restart: always
        depends_on:
              - rabbitmq
  model:
        build:
            context: ./model
        restart: always
        depends_on:
              - rabbitmq
              - features
  metric:
        build:
            context: ./metric
        restart: always
        depends_on:
              - rabbitmq
              - features
              - model
        volumes: 
              - ./logs/:/usr/src/app/logs/
              - ./logs/pred_logs/:/usr/src/app/logs/pred_logs/
              - ./logs/true_logs/:/usr/src/app/logs/true_logs/